### ISSUE TITLE
SNAPSHOT of 20210525: Dashboard not working

### ISSUE THREAD

**Issue by xatapult** [eXist-db/existdb-packageservice#19]
**Describe the bug**
In the 5.3.0 SNAPSHOT of 20210525 the Dashboard is not working.

**To Reproduce**
Install with this snapshot. Try to view the Dashboard.
JAR name: `exist-installer-5.3.0-SNAPSHOT+20210525025502.jar`

**Context (please always complete the following information):**
 - OS: Windows 10 but also on Linux
 - eXist-db version: 5.3.0 SNAPSHOT version of 20210525
 - Java Version:  various, one of them reports:
 ```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM Corretto-8.292.10.1 (build 25.292-b10, mixed mode)
```

**Additional context**
- How is eXist-db installed? JAR
- Any custom changes: not yet

**Comment by adamretter** [comment]
> It's surprising that the tests for eXist-db/exist#3896 passed. We must be lacking an integration test that would open dashboard and open all resources that dashboard's landing page does. 

Indeed. There are no integration tests for the Dashboard AFAIK, and such tests would need to live in the app repos and CI rather than the eXist core repo.

**Comment by joewiz** [comment]
existdb-packageservice v1.3.11 containing the hotfix for this issue has been published to the public-repo and this repo's releases:

- https://exist-db.org/exist/apps/public-repo/packages/packageservice.html?eXist-db-min-version=5.0.0
- https://github.com/eXist-db/existdb-packageservice/releases/tag/v1.3.11

**Comment by duncdrum** [comment]
@adamretter @joewiz There are integration test for all default auto-deploy apps since exist version `5.0.0`. You can find past runs on the Cypress Dashboard. There was talk among @eXist-db/exist-webcomponents to replace the cypress tests with another solution, but that never materialized. 
There was a break in the test coverage when a) we stopped pushing docker images and b) we ran out of credits for Travis, but both problems are solved now. Ensuring that the tests are running, or replaced by the **new** hotness, is up to the maintainers of the dashboard.

**Comment by joewiz** [comment]
@duncdrum Wow, sounds like the CI infrastructure in Dashboard hasn't kept up with the advancements in the core and some of the other apps. 

I'm just curious, would an integration test in Dashboard have detected this regression? It was a change to core that had an inadvertent effect on Dashboard. If the tests are in Dashboard, wouldn't it take a push to Dashboard to cause its tests to run, or are the tests in core also able to check Dashboard?

**Comment by adamretter** [comment]
@duncdrum Okay... I only saw one test in Dashboard Cypress folder that just checks that it can click the Package Manager icon. Do you know if there are some others I missed or is that enough to catch this issue?

So it also sounds like each app needs to be migrated to new CI (i.e. GitHub Actions by the Package Maintainer)?

**Comment by duncdrum** [comment]
Since the dashboard doesn’t do much other than launch the apps, this test would have caught the issue. Yes as discussed on the community call, all our ci infrastructure needs to migrated before the travis credits run out again. 

More test of the web component apps would be great, they are wip since 5.0.0. 

App test are not configure to run on pushes to core, but that can be configured. I’d prefer to have them run once a week on a crown job. I would not include integration tests of apps into the core ci, it’s crowded enough as is. Of course if maintainers don’t act on failing tests, then the information is somewhat pointless.

**Comment by line-o** [comment]
I believe this issue is fixed. Please reopen if you don't agree.
